In [9]:
import joblib
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [10]:
X_train_tfidf = joblib.load("models/X_train_tfidf.pkl")
X_test_tfidf = joblib.load("models/X_test_tfidf.pkl")

y_train = joblib.load("models/y_train.pkl")
y_test = joblib.load("models/y_test.pkl")

In [11]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

print(len(y_train))
print(len(y_test))

(36605, 5000)
(9152, 5000)
36605
9152

In [4]:
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        random_state=42
    ),

    "Naive Bayes": MultinomialNB(),

    "Linear SVM": LinearSVC(
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    )
}

In [12]:
results = []

for name, model in models.items():

    model.fit(X_train_tfidf, y_train)

    prediction = model.predict(X_test_tfidf)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, prediction),
        "Precision": precision_score(y_test, prediction),
        "Recall": recall_score(y_test, prediction),
        "F1 Score": f1_score(y_test, prediction)
    })

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.975087   0.975317  0.974891  0.975104
1          Naive Bayes  0.924279   0.927049  0.921179  0.924105
2           Linear SVM  0.983173   0.985307  0.981004  0.983151
3        Random Forest  0.979677   0.991059  0.968122  0.979457

In [13]:
results_df.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
2           Linear SVM  0.983173   0.985307  0.981004  0.983151
3        Random Forest  0.979677   0.991059  0.968122  0.979457
0  Logistic Regression  0.975087   0.975317  0.974891  0.975104
1          Naive Bayes  0.924279   0.927049  0.921179  0.924105

In [14]:
best_model = LinearSVC(
    random_state=42
)

best_model.fit(X_train_tfidf, y_train)

joblib.dump(
    best_model,
    "models/fake_news_model.pkl"
)

['models/fake_news_model.pkl']

In [15]:
print("Best Model Saved Successfully!")

Best Model Saved Successfully!