In [3]:
import pandas as pd

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
import joblib

In [7]:
df = pd.read_csv("data/processed/clean_news.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/clean_news.csv'

In [ ]:
print(df["label"].value_counts())

label
1    22900
0    22857
Name: count, dtype: int64

In [ ]:
print(df[["text", "label"]].head())

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [ ]:
df.head()

,text,label,clean_text
0,Gere faults Trump for blurring meaning of 'ref...,1,gere fault trump blurring meaning refugee terr...
1,German parties start to find common ground in ...,1,german party start find common ground coalitio...
2,Senate Democratic leader says Attorney General...,1,senate democratic leader say attorney general ...
3,"Tennis: Kyrgios fined $10,000 for Shanghai wal...",1,tennis kyrgios fined shanghai walk tennis chin...
4,Trump Threw Mar-A-Lago Fundraiser For Woman A...,0,trump threw maralago fundraiser woman center b...

In [ ]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [ ]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [ ]:
X = df["clean_text"]

y = df["label"]

In [ ]:
print(X.head())

print()

print(y.head())

0    gere fault trump blurring meaning refugee terr...
1    german party start find common ground coalitio...
2    senate democratic leader say attorney general ...
3    tennis kyrgios fined shanghai walk tennis chin...
4    trump threw maralago fundraiser woman center b...
Name: clean_text, dtype: str

0    1
1    1
2    1
3    1
4    0
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
print("Training samples :", len(X_train))
print("Testing samples  :", len(X_test))

Training samples : 36605
Testing samples  : 9152

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=5,
    max_df=0.8
)

In [ ]:
df["clean_text"].isna().sum()

np.int64(5)

In [ ]:
df["clean_text"] = df["clean_text"].fillna("")

In [ ]:
print(df["clean_text"].isna().sum())

0

In [ ]:
print(df["clean_text"].dtype)

str

In [ ]:
print(df["clean_text"].head())

0    gere fault trump blurring meaning refugee terr...
1    german party start find common ground coalitio...
2    senate democratic leader say attorney general ...
3    tennis kyrgios fined shanghai walk tennis chin...
4    trump threw maralago fundraiser woman center b...
Name: clean_text, dtype: str

In [ ]:
X = df["clean_text"]
y = df["label"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [ ]:
print("Training Shape :", X_train_tfidf.shape)
print("Testing Shape  :", X_test_tfidf.shape)

Training Shape : (36605, 5000)
Testing Shape  : (9152, 5000)

In [ ]:
print("Vocabulary Size:", len(tfidf.vocabulary_))

Vocabulary Size: 5000

In [ ]:
feature_names = tfidf.get_feature_names_out()

print(feature_names[:20])

['abandon' 'abandoned' 'abc' 'abc news' 'abe' 'abedin' 'ability' 'able'
 'abortion' 'abroad' 'absence' 'absolute' 'absolutely' 'abu' 'abuse'
 'academic' 'academy' 'accept' 'acceptable' 'accepted']

In [ ]:
import joblib

joblib.dump(tfidf, "models/tfidf_vectorizer.pkl")

['models/tfidf_vectorizer.pkl']

In [ ]:
print(type(X_train_tfidf))
print(type(y_train))

<class 'scipy.sparse._csr.csr_matrix'>
<class 'pandas.Series'>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [ ]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
logistic_prediction = logistic_model.predict(X_test_tfidf)

In [ ]:
print("Logistic Regression Accuracy:",
      accuracy_score(y_test, logistic_prediction))

Logistic Regression Accuracy: 0.9750874125874126

In [ ]:
print(classification_report(y_test, logistic_prediction))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      4572
           1       0.98      0.97      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152

In [ ]:
print(confusion_matrix(y_test, logistic_prediction))

[[4459  113]
 [ 115 4465]]

In [ ]:
naive_model = MultinomialNB()

naive_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
naive_prediction = naive_model.predict(X_test_tfidf)

In [ ]:
print("Naive Bayes Accuracy:",
      accuracy_score(y_test, naive_prediction))

Naive Bayes Accuracy: 0.9242788461538461

In [ ]:
print(classification_report(y_test, naive_prediction))

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      4572
           1       0.93      0.92      0.92      4580

    accuracy                           0.92      9152
   macro avg       0.92      0.92      0.92      9152
weighted avg       0.92      0.92      0.92      9152

In [ ]:
print(confusion_matrix(y_test, naive_prediction))

[[4240  332]
 [ 361 4219]]

In [ ]:
svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

svm_prediction = svm_model.predict(X_test_tfidf)

print("Linear SVM Accuracy:",
      accuracy_score(y_test, svm_prediction))

print(classification_report(y_test, svm_prediction))

print(confusion_matrix(y_test, svm_prediction))

Linear SVM Accuracy: 0.9831730769230769
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      4572
           1       0.99      0.98      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152

[[4505   67]
 [  87 4493]]

In [ ]:
forest = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

forest.fit(X_train_tfidf, y_train)

forest_prediction = forest.predict(X_test_tfidf)

print("Random Forest Accuracy:",
      accuracy_score(y_test, forest_prediction))

print(classification_report(y_test, forest_prediction))

print(confusion_matrix(y_test, forest_prediction))

Random Forest Accuracy: 0.9796765734265734
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      4572
           1       0.99      0.97      0.98      4580

    accuracy                           0.98      9152
   macro avg       0.98      0.98      0.98      9152
weighted avg       0.98      0.98      0.98      9152

[[4532   40]
 [ 146 4434]]

In [ ]:
import joblib

joblib.dump(X_train_tfidf, "models/X_train_tfidf.pkl")
joblib.dump(X_test_tfidf, "models/X_test_tfidf.pkl")

joblib.dump(y_train, "models/y_train.pkl")
joblib.dump(y_test, "models/y_test.pkl")

['models/y_test.pkl']

# Bag of Words (BoW)

Bag of Words converts text into numerical vectors based on the frequency of each word in the dataset. Unlike TF-IDF, it only counts word occurrences and does not reduce the importance of frequently occurring words.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [1]:
%whos

Interactive namespace is empty.

In [5]:
import pandas as pd

df = pd.read_csv("../data/processed/clean_news.csv")
df.head()

,text,label,clean_text
0,Gere faults Trump for blurring meaning of 'ref...,1,gere fault trump blurring meaning refugee terr...
1,German parties start to find common ground in ...,1,german party start find common ground coalitio...
2,Senate Democratic leader says Attorney General...,1,senate democratic leader say attorney general ...
3,"Tennis: Kyrgios fined $10,000 for Shanghai wal...",1,tennis kyrgios fined shanghai walk tennis chin...
4,Trump Threw Mar-A-Lago Fundraiser For Woman A...,0,trump threw maralago fundraiser woman center b...

In [6]:
import os

print(os.path.exists("../data/processed/clean_news.csv"))
print(os.path.exists("../data/raw/news.csv"))

True
True

In [8]:
df.columns

Index(['text', 'label', 'clean_text'], dtype='str')

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
df["clean_text"].isnull().sum()

np.int64(5)

In [12]:
df = df.dropna(subset=["clean_text"])

In [13]:
df = df[df["clean_text"].notna()]

In [14]:
df["clean_text"].isnull().sum()

np.int64(0)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(max_features=5000)

X_bow = bow.fit_transform(df["clean_text"])

print(X_bow.shape)

(45752, 5000)

In [16]:
df[["clean_text"]].head()

                                          clean_text
0  gere fault trump blurring meaning refugee terr...
1  german party start find common ground coalitio...
2  senate democratic leader say attorney general ...
3  tennis kyrgios fined shanghai walk tennis chin...
4  trump threw maralago fundraiser woman center b...

In [18]:
sample_df = pd.DataFrame(
    X_bow[:5, :20].toarray(),
    columns=bow.get_feature_names_out()[:20]
)

sample_df

,aaron,abandon,abandoned,abbas,abc,abdullah,abe,abedin,ability,able,abortion,abroad,absence,absolute,absolutely,absurd,abu,abuse,abused,academic
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
print("Bag of Words Matrix Shape:", X_bow.shape)

Bag of Words Matrix Shape: (45752, 5000)

In [20]:
print("Vocabulary Size:", len(bow.get_feature_names_out()))

Vocabulary Size: 5000

In [21]:
print(bow.get_feature_names_out()[:20])

['aaron' 'abandon' 'abandoned' 'abbas' 'abc' 'abdullah' 'abe' 'abedin'
 'ability' 'able' 'abortion' 'abroad' 'absence' 'absolute' 'absolutely'
 'absurd' 'abu' 'abuse' 'abused' 'academic']